customhost = "employeedb.cfuuu0agkhkb.us-west-1.rds.amazonaws.com"
customuser = "admin"
custompass = "Ravidas67"
customdb = "employeedb"
custombucket = "project-june123456"
customregion = "us-west-1"
